<template>
    <div id="kt_content" class="content d-flex flex-column flex-column-fluid">
      <div class="d-flex flex-column-fluid pt-md-5">
        <div class="container">
          <div id="list" class="animated">
            <div class="card card-custom mb-5">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="text-center">
                        <h1 class="display-1 font-weight-boldest mb-12">Under Maintance</h1>
                        <p class="font-size-h3">We are currently under maintance. Please come back later.</p>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  
  // Image Map Generated by http://www.image-map.net/
  import PinchScrollZoom from '@coddicat/vue-pinch-scroll-zoom'
  
  export default {
    name: 'Under-Maintance',
    components: {
      PinchScrollZoom
    },
    data () {
      return {

      }
    },
    async beforeMount () {
    },
    mounted () {

    }
  }
  </script>
  
  <style>

  